#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Vertd, video conversion services" --log="/var/log/$app/$app.log"

#=================================================
# BUILD VERTD
#=================================================
ynh_script_progression "Compiling binary (it may take a while)..."

debian_version=$(cat /etc/os-release | sed -n 3p | sed -e 's/VERSION_ID="//' -e 's/"//')

# Upstream prebuilt binary requires GLIBC version 2.39 when Debian Bookworm ships 2.36 and Trixie 2.41
if [[ $debian_version -ge 13 ]]; then
    # Use upstream prebuilt version
    ynh_setup_source --dest_dir="$install_dir" --source_id="vertd_prebuilt"
else
    # Build locally and lower GLIBC requirements
    pushd "$install_dir"

        # Set the build repo up
        ynh_setup_source --dest_dir="$install_dir/vertd_source" --source_id="vertd_source"
        cd vertd_source

        # Install Rustup and Cargo
        export PATH="$PATH:$install_dir/.cargo/bin:$install_dir/.local/bin:/usr/local/sbin"
        if [ -e $install_dir/.rustup ]; then
            ynh_hide_warnings ynh_exec_as_app PATH=$PATH rustup update
        else
            ynh_hide_warnings ynh_exec_as_app bash -c 'curl -sSf -L https://static.rust-lang.org/rustup.sh | sh -s -- -y --default-toolchain=stable --profile=minimal'
        fi

        # Create config file to mimit GLIBC symbols to the version 2.36 of the lib
        echo 'GLIBC_2.36 {'    > glibc.version
        echo '    global: *;' >> glibc.version
        echo '};'             >> glibc.version

        # Build
        chown -R $app:$app "$install_dir"
        ynh_hide_warnings ynh_exec_as_app bash -c "
            source \"$install_dir/.cargo/env\"
            RUSTFLAGS=\"-C link-arg=-Wl,--version-script=$install_dir/vertd_source/glibc.version\" \"$install_dir/.cargo/bin/cargo\" build --release
        "

        # Clean
        cd "$install_dir"
        cp -af vertd_source/target/release/vertd ./vertd
        ynh_safe_rm vertd_source
    popd
fi

chmod +x "$install_dir/vertd"

#=================================================
# INSTALL VERT
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
    ynh_hide_warnings npm install -g bun
    ynh_hide_warnings bun install
    ynh_hide_warnings bun run build
popd

chown $app:www-data "$install_dir" #just to allow www-data access child 'build' dir
chown -R $app:www-data "$install_dir/build"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
